### ISSUE TITLE
Update to 1.6.0

### ISSUE THREAD

**Issue by carlwgeorge** [iusrepo/php73-pecl-mongodb#1]
This RPM spec file needs to be updated to [upstream version 1.6.0](https://pecl.php.net/package/mongodb/1.6.0).  If you aren't familiar with RPM spec files, check out [this guide](https://rpm-packaging-guide.github.io).

**Comment by blackfile** [comment]
Working in this issue

**Comment by blackfile** [comment]
completed #2

**Comment by carlwgeorge** [comment]
Thanks @blackfile.  The update has been published to the testing repository.
